import type { Metadata } from "next";
import "./globals.css";
// import Link from "next/link";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
      </head>
      <body>
        {/* <nav className="fullNav">
          <Link href='/about'>About</Link>
          <Link href='/projects'>Projects</Link>
          <Link href='#skills'>Skills</Link>
          <Link href='#contact'>Contact</Link>
        </nav> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
